### PR TITLE
feat: add conf to remain rule metrics

### PR DESCRIPTION
**Pull request by Yisaer**

### CODE REVIEW

**Review by ngjaying — COMMENTED** [review]
Did you consider delete and then create a rule with the same id? Will this clean the old stats?

**Comment by Yisaer** [comment]
> Did you consider delete and then create a rule with the same id? Will this clean the old stats?

We thought it as the same rule.

**Comment by ngjaying** [comment]
> > Did you consider delete and then create a rule with the same id? Will this clean the old stats?
> 
> We thought it as the same rule.

Will the metrics increasing from the last state. For example, the old instance has 100 records in, after re-create the rule, will you start from 101?

**Comment by Yisaer** [comment]
> > > Did you consider delete and then create a rule with the same id? Will this clean the old stats?
> > 
> > 
> > We thought it as the same rule.
> 
> Will the metrics increasing from the last state. For example, the old instance has 100 records in, after re-create the rule, will you start from 101?

yes

**Pull request closed without merging**
