### PR TITLE
fix(sink): shadowed variable cause the inner err unhandled

### PR DESCRIPTION
**Pull request by carlclone**

### CODE REVIEW

**Review by ngjaying — COMMENTED** [review]
Do you think it will be better to just return the error explicitly instead of setting the return variable name?

**Comment by ngjaying** [comment]
> > Do you think it will be better to just return the error explicitly instead of setting the return variable name?
> 
> thanks for advice , i push a new version , is this ok ?

You're welcome. Looks good.
Just curious, how do you find this bug

**Comment by carlclone** [comment]
ok

**Comment by ngjaying** [comment]
@carlclone Just to clarify. It is optional to add your name to the license statement. It is okay to put your Github id instead of your name as it is just to give you credit for this project. Thanks for your great contributions

**Comment by carlclone** [comment]
> @carlclone Just to clarify. It is optional to add your name to the license statement. It is okay to put your Github id instead of your name as it is just to give you credit for this project. Thanks for your great contributions

but this file is not created by me , i wil add copyright in my kafka sink file , thanks

**Review by ngjaying — APPROVED** [review]

**Pull request merged**
