### PR TITLE
feat: add android packaging

### LINKED ISSUE #1123: [OSPP]Support android

### PR DESCRIPTION
**Pull request by bing-zhub**
android_ekuiper

Many users want to deploy ekuiper on Android, in order to facilitate this part of the user, this PR compiles the ekuiper cross-platform to Android, and packages it to produce apk files.

Implementation:
Based on the cross-platform GUI toolkit [fyne](https://developer.fyne.io/started/mobile), using absolute path to read/write configuration files/logs, all configuration files and runtime files will be saved to `/storage/emulated/0/ekuiper/` directory, if you need to modify the configuration information, please use the file manager to modify the corresponding file and then restart ekuiper.

Problems:
Can't get file storage permission automatically, need to enable it manually.

Closes #1123

### CODE REVIEW

**Review by ngjaying — COMMENTED** [review]
Good job! 
What is the ttf file for? Is it required or can we remove it? Is it licensed? Thanks.

**Comment by bing-zhub** [comment]
Thanks!

> What is the ttf file for? Is it required or can we remove it?

When the UI needs to display non-ascii characters, it will be messed up without this font package (`.tff`), if the target users of this application are all English users, there is no problem to delete this font package and modify the corresponding theme file (`theme.go`).

> Is it licensed? 

This font is open source, its repository is at [smiley-sans](https://github.com/atelier-anchor/smiley-sans), it follows the SIL Open Font License 1.1. Users have the [following permissions](https://github.com/atelier-anchor/smiley-sans/blob/main/LICENSE):
- Private use
- Commercial use
- Modification
- Distribution

**Comment by ngjaying** [comment]
> Thanks!
> 
> > What is the ttf file for? Is it required or can we remove it?
> 
> When the UI needs to display non-ascii characters, it will be messed up without this font package (`.tff`), if the target users of this application are all English users, there is no problem to delete this font package and modify the corresponding theme file (`theme.go`).
> 
> > Is it licensed?
> 
> This font is open source, its repository is at [smiley-sans](https://github.com/atelier-anchor/smiley-sans), it follows the SIL Open Font License 1.1. Users have the [following permissions](https://github.com/atelier-anchor/smiley-sans/blob/main/LICENSE):
> 
> * Private use
> * Commercial use
> * Modification
> * Distribution

Looks like we need to delete the font as it does not allow commercial use which is conflict with Apache 2.0 license. Maybe we can add some instruction to the readme to guide users to add their own font.

**Comment by bing-zhub** [comment]
> Looks like we need to delete the font as it does not allow commercial use which is conflict with Apache 2.0 license. Maybe we can add some instruction to the readme to guide users to add their own font.

Sorry, I don't know much about these licenses. I'll follow up with a commit under this PR, remove the font package, and add documentation in `README.md` that supports non-ascii characters.

**Review by Rory-Z — APPROVED** [review]

**Comment by ngjaying** [comment]
Thank you!

**Pull request merged**
