### PR TITLE
docs: fix Chinese doc errors for substring func

### PR DESCRIPTION
**Pull request by Dream95**
substring function not support Negative integer

### CODE REVIEW

**Comment by ngjaying** [comment]
Thanks. Actually, we expect to support negative index. So instead of modifying the doc, shall we modify the code?

**Comment by Dream95** [comment]
What will be substring('abcde',2,-1)  return？

**Comment by ngjaying** [comment]
> What will be substring('abcde',2,-1) return？

-1 means (length-1).  This will return index [2 to 4] which is "cde". Is it reasonable?

**Comment by ngjaying** [comment]
Currently，let's just fix the doc. @Dream95 Could you please take a look at the Details of DCO check and try to pass it. Thanks.

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
