### PR TITLE
feat: create plugin using local file

### PR DESCRIPTION
**Pull request by jerempy**
Adds ability to create plugins using something like `./kuiper create plugin sink influx -zf ./influx.zip`

Closes: https://github.com/lf-edge/ekuiper/issues/1765

The approach I took was to add an additional flag "-zf" or "zipfile".
if passed it will take the path to the file and wrap it in the expected json and then run the function normally if it was passed as a json file.

### CODE REVIEW

**Comment by ngjaying** [comment]
> unfortunately i dont understand the stack trace on the failing test action - any insight?

No problem, we'll take a look.

**Comment by Rui-Gan** [comment]
> unfortunately i dont understand the stack trace on the failing test action - any insight?

In the `fileExists` function, true is returned if the file does not exist. In the `readDef` function, if the `fileExists` function returns false, that is, if the file exists, it returns error; In short, this `fileExists` function should return `!os.IsNotExist(err)`.

**Comment by Rui-Gan** [comment]
The current implementation does not appear to allow the use of local files for creating plugins. 

To create a plugin, you cannot directly use local files with ekuiper. Instead, you need to host the local file on an HTTP server and use the URL of the plugin file to create the plugin.

Hence, if you attempt to reuse the previous code implementation for plugin creation, it will not currently support the use of local files.

The statement above reflects my understanding.  If there are any inaccuracies or mistakes, please don't hesitate to correct them.

**Comment by ngjaying** [comment]
> The current implementation does not appear to allow the use of local files for creating plugins.
> 
> To create a plugin, you cannot directly use local files with ekuiper. Instead, you need to host the local file on an HTTP server and use the URL of the plugin file to create the plugin.
> 
> Hence, if you attempt to reuse the previous code implementation for plugin creation, it will not currently support the use of local files.
> 
> The statement above reflects my understanding. If there are any inaccuracies or mistakes, please don't hesitate to correct them.

If CLI is run in the same machine of kuiperd, it is possible to load the local file. Besides http://xxx, the file also allows file:/// protocol. So when calling local kuiperd, we may just convert local file to file:/// format to meet the current API.

**Review by Rui-Gan — APPROVED** [review]
Great, please add another PR to update the doc. Thanks.

**Comment by ngjaying** [comment]
@jerempy Thanks very much!

**Pull request merged**
