### PR TITLE
fix,refactor(sqlite) https://github.com/lf-edge/ekuiper/issues/842 fi…

### PR DESCRIPTION
**Pull request by ngjaying**
…x and refactoring

Fix (and refactoring) related to the too many files open issue - since sqlite does not work well with concurrent writes - kv store was rewritten to use single connection for access to the database,
* introduced database structure which will take away sql database specifics (sqlite in this case)
* fix in topo.go - there was possible scenario that during Open execution of underlying goroutine Cancel was called and store property was set to nil which was leading to null pointer exception

Signed-off-by: Robert Wadowski <robert.wadowski1@gmail.com>
Signed-off-by: Jiyong Huang <huangjy@emqx.io>

### CODE REVIEW

**Comment by rwadowski** [comment]
@ngjaying fvt tests seems to fail, what are these tests ? How can I rerun them locally ?

**Comment by ngjaying** [comment]
> @ngjaying fvt tests seems to fail, what are these tests ? How can I rerun them locally ?

They are documented [here](https://github.com/lf-edge/ekuiper/blob/master/test/README.md). I am actually trying to fix them. They seem to work locally but fail in github.

**Comment by rwadowski** [comment]
@ngjaying quick question (I hope) - if somebody will update pull request, how can I fetch other changes ? Do I have to sync the upstream or just pull branch on my fork ?

**Comment by ngjaying** [comment]
> @ngjaying quick question (I hope) - if somebody will update pull request, how can I fetch other changes ? Do I have to sync the upstream or just pull branch on my fork ?

I suppose to push my changes to your branch. This one is actually experimental for me to test the FVTs.

**Pull request closed without merging**
