### PR TITLE
perf: Reuse buffer during lexical analysis

### PR DESCRIPTION
**Pull request by huskar-t**

### CODE REVIEW

**Comment by huskar-t** [comment]
image
benchmark result

**Comment by xjasonlyu** [comment]
Wondering if `Scanner` is only called by a single goroutine?

**Comment by huskar-t** [comment]
@xjasonlyu 
I don't see where the lexical analysis is performed concurrently, and I don't see a lock in the `Scanner` either.

**Comment by ngjaying** [comment]
@huskar-t Thanks for the PR. Please avoid mixing commits of different purpose into one PR. Suggest to create another PR for your last commit.

**Comment by huskar-t** [comment]
> @huskar-t Thanks for the PR. Please avoid mixing commits of different purpose into one PR. Suggest to create another PR for your last commit.

The latest commit is to solve the failure of github actions, do I need to submit a new PR?

**Comment by ngjaying** [comment]
> > @huskar-t Thanks for the PR. Please avoid mixing commits of different purpose into one PR. Suggest to create another PR for your last commit.
> 
> The latest commit is to solve the failure of github actions, do I need to submit a new PR?

I prefer a new PR.

**Comment by huskar-t** [comment]
waiting for #2033 to be merged

**Review by ngjaying — APPROVED** [review]
Appreciate your great contribution

**Pull request merged**
