### PR TITLE
docs(zh_CN): Description is different from the preview

### PR DESCRIPTION
**Pull request by guowei-gong**
describe: https://github.com/lf-edge/ekuiper/issues/1368

Signed-off-by: 龚国玮 <gongguowei01@gmail.com>

### CODE REVIEW

**Review by ngjaying — COMMENTED** [review]
Thanks Guowei! I find the English version has the same problem, could you also change the screenshot there?

**Comment by guowei-gong** [comment]
> Thanks Guowei! I find the English version has the same problem, could you also change the screenshot there?

OK

**Comment by guowei-gong** [comment]
Do I need to merge into the same request?

**Comment by ngjaying** [comment]
> Do I need to merge into the same request?

It's fine, we can squash and merge after review

**Comment by ngjaying** [comment]
DCO check fails, please follow the instruction in the details to get it passed.

**Pull request closed without merging**
