### PR TITLE
feat(sink): support databend as sink

### PR DESCRIPTION
**Pull request by hantmac**
- fix https://github.com/lf-edge/ekuiper/issues/2178

I found that databend has already been added into [dburl](https://github.com/xo/dburl), so it is very convenient to support it as a sink. BTW, how can I add some integration tests for databend sink?

### CODE REVIEW

**Comment by ngjaying** [comment]
SQL sinks are not well tested because there are A LOT of db types supported... Regarding integration test, you may try the FVT with jmeter script https://github.com/lf-edge/ekuiper/blob/master/test/README.md. It is not easy to setup.

By the way, we have code freezed now for features as we are going to release 1.11.0 soon. We will not merge this until next week.

**Comment by hantmac** [comment]
> SQL sinks are not well tested because there are A LOT of db types supported... Regarding integration test, you may try the FVT with jmeter script https://github.com/lf-edge/ekuiper/blob/master/test/README.md. It is not easy to setup.
> 
> By the way, we have code freezed now for features as we are going to release 1.11.0 soon. We will not merge this until next week.

Thanks! Got it. I will try the FVT with jmeter script.

**Comment by ngjaying** [comment]
> > SQL sinks are not well tested because there are A LOT of db types supported... Regarding integration test, you may try the FVT with jmeter script https://github.com/lf-edge/ekuiper/blob/master/test/README.md. It is not easy to setup.
> > By the way, we have code freezed now for features as we are going to release 1.11.0 soon. We will not merge this until next week.
> 
> Thanks! Got it. I will try the FVT with jmeter script.

We had a brief intro for FVT in this community meeting recording from 16:00. Hope it helps. https://zoom.us/rec/share/0nKvii6j3vm_1NjXxDk8CvhSzAbnrq2A3jFnBIy1zgD6mnjYGZ3hqQnJ3ILLhEBf.n1JEBqTYgYcEr8Fv

**Comment by hantmac** [comment]
@ngjaying Hi bro, Is there any plan to merge this pr?

**Comment by ngjaying** [comment]
> @ngjaying Hi bro, Is there any plan to merge this pr?

Sure, I thought you were adding tests, so just wait. Have you tested manually to write to databend?

**Comment by hantmac** [comment]
> > @ngjaying Hi bro, Is there any plan to merge this pr?
> 
> Sure, I thought you were adding tests, so just wait. Have you tested manually to write to databend?

Oh, I will add some related tests. Just hold on. I have not tested mannually 😢 . I want to know is there any cloud platform for equiper? I want to  test databend after this pr merged on cloud platform, it is more convenient 😄

**Comment by ngjaying** [comment]
> > > @ngjaying Hi bro, Is there any plan to merge this pr?
> > 
> > 
> > Sure, I thought you were adding tests, so just wait. Have you tested manually to write to databend?
> 
> Oh, I will add some related tests. Just hold on. I have not tested mannually 😢 . I want to know is there any cloud platform for equiper? I want to test databend after this pr merged on cloud platform, it is more convenient 😄

There is no cloud platform. @Yisaer could you help to provide some materials about how to test the SQL source/sink with this additional driver?

**Comment by Yisaer** [comment]
I think you can manually test it by following this document: https://ekuiper.org/docs/zh/latest/guide/sinks/plugin/sql.html#%E7%BC%96%E8%AF%91%E9%83%A8%E7%BD%B2%E6%8F%92%E4%BB%B6

After you build the plugins of sql-databend, and pasted it into `plugins/sinks/sql`. You can define the rule with `sql sink` action to insert data into databend, here is an example for sql sink action https://ekuiper.org/docs/zh/latest/guide/sinks/plugin/sql.html#%E4%BD%BF%E7%94%A8%E6%A0%B7%E4%BE%8B

**Comment by hantmac** [comment]
> I think you can manually test it by following this document: https://ekuiper.org/docs/zh/latest/guide/sinks/plugin/sql.html#%E7%BC%96%E8%AF%91%E9%83%A8%E7%BD%B2%E6%8F%92%E4%BB%B6
> 
> After you build the plugins of sql-databend, and pasted it into `plugins/sinks/sql`. You can define the rule with `sql sink` action to insert data into databend, here is an example for sql sink action https://ekuiper.org/docs/zh/latest/guide/sinks/plugin/sql.html#%E4%BD%BF%E7%94%A8%E6%A0%B7%E4%BE%8B


Hi @Yisaer, thanks for your help. I test is manually according the next steps:

1.  Run `make` to build
2. Run the kuiperd locally: `./bin/kuiperd`
3. config the `file.yaml` in `$buildPath/sources/file.yaml`:

```
default:
  # The type of the file, could be json, csv and lines
  fileType: json
  # The directory of the file relative to kuiper root or an absolute path.
  # Do not include the file name here. The file name should be defined in the stream data source
  path: buildpath/etc/sources/data
  # The interval between reading the files, time unit is ms. If only read once, set it to 0
  interval: 0
  # The sending interval between each event in millisecond
  sendInterval: 0
  # Read the files in a directory in parallel or not
  parallel: false
  # After read
  # 0: keep the file
  # 1: delete the file
  # 2: move the file to moveTo
  actionAfterRead: 0
  # The path to move the file to after read, only valid when the actionAfterRead is 2
  moveTo: /tmp/kuiper/moved
  # If the first line is header
  hasHeader: false
  # Define the columns. If header is defined, this will be override
  # columns: [id, name]
  # How many lines to be ignored at the beginning. Notice that, empty line will be ignored and not be calculated.
  ignoreStartLines: 0
  # How many lines to be ignored in the end. Notice that, empty line will be ignored and not be calculated.
  ignoreEndLines: 0

```
image
5. Create scan table using CLI: `./bin/kuiper create table table1 '(name STRING,size BIGINT,id BIGINT) WITH (DATASOURCE="test.json", FORMAT="json", TYPE="file");'`
6. Build the databend plugin using: `go build -trimpath --buildmode=plugin -tags databend -o plugins/sinks/Sql.so extensions/sinks/sql/sql.go` and copy the Sql.so to `buildpath/plugins/sinks`
7. Create rule: `bin/kuiper create rule myRule -f myRule.json`

```
{
  "id": "rule",
  "sql": "SELECT id, name from table1",
  "actions": [
    {
      "log": {
      },
      "sql": {
        "url": "jdbc:databend://databend:databend@localhost:8000/default",
        "table": "test",
        "fields": ["id","name"]
      }
    }
  ]
}
```
8. But I got an error when creating rule:

```
 bin/kuiper getstatus rule myRule
Connecting to 127.0.0.1:20498... 
{"status": "stopped", "message": "Stopped: unknown database scheme."}
```

I guess the `databend ` plugin seems not load? Or have not built in?

**Comment by ngjaying** [comment]
@hantmac Need to add tag for databend when compiling the SQL plugin. Check this example: https://ekuiper.org/docs/en/latest/guide/sinks/plugin/sql.html#compile-deploy-plugin

**Comment by hantmac** [comment]
> @hantmac Need to add tag for databend when compiling the SQL plugin. Check this example: https://ekuiper.org/docs/en/latest/guide/sinks/plugin/sql.html#compile-deploy-plugin

@ngjaying  Yes I build with the tags `-tags databend` which is `go build -trimpath --buildmode=plugin -tags databend -o plugins/sinks/Sql.so extensions/sinks/sql/sql.go`

**Comment by hantmac** [comment]
@ngjaying It's my fault. I use a wrong databend dsn. And now the manual test passed.
image

**Comment by Yisaer** [comment]
@hantmac I think the error is from `dburl` as following:
```golang
	// ErrUnknownDatabaseScheme is the unknown database type error.
	ErrUnknownDatabaseScheme Error = "unknown database scheme"
```

For now we use `dburl v0.13.0`, maybe it doesn't contained `databend` driver?

**Review by Yisaer — APPROVED** [review]

**Review by ngjaying — APPROVED** [review]

**Pull request merged**
