### PR TITLE
feat(sql): implement sql funcs for date and time

### PR DESCRIPTION
**Pull request by yai-dev**
Implement SQL functions for date and time, here is list of implemented functions:

- NOW
- CURRENT_TIMESTAMP
- LOCAL_TIME
- LOCAL_TIMESTAMP
- CUR_DATE
- CURRENT_DATE
- CUR_TIME
- CURRENT_TIME
- FORMAT_TIME (moved from `funcs_str.go`)
- DATE_CALC
- DATE_DIFF
- DAY_NAME
- DAY_OF_MONTH
- DAY
- DAY_OF_WEEK
- DAY_OF_YEAR
- FROM_DAYS
- FROM_UNIX_TIME
- HOUR
- LAST_DAY
- MICROSECOND
- MINUTE
- MONTH
- MONTH_NAME
- SECOND

### CODE REVIEW

**Comment by ngjaying** [comment]
Wow, a lot of functions. Amazing!

**Review by ngjaying — CHANGES_REQUESTED** [review]
The codecov does not meet the criteria. Is it possible to add tests against the validations? There are example in other function tests. Thanks.

**Comment by yai-dev** [comment]
> The codecov does

OK 👍

**Review by Yisaer — APPROVED** [review]

**Review by ngjaying — APPROVED** [review]

**Comment by ngjaying** [comment]
Merged, thank you very much!

**Pull request merged**
