### PR TITLE
chore: add check for go tidy

### PR DESCRIPTION
**Pull request by Yisaer**

### CODE REVIEW

**Comment by Rory-Z** [comment]
Why we need this ?
I think we can running `go mod tidy && git diff .` is ok

**Comment by Yisaer** [comment]
> Why we need this ? I think we can running `go mod tidy && git diff .` is ok

We can use it to guarantee mod tidy if we integrate it into CI check progress

**Comment by Rory-Z** [comment]
> > Why we need this ? I think we can running `go mod tidy && git diff .` is ok
> 
> We can use it to guarantee mod tidy if we integrate it into CI check progress later

Looks this just show diff of go.sum, so why not use `git diff`

**Comment by Yisaer** [comment]
> > > Why we need this ? I think we can running `go mod tidy && git diff .` is ok
> > 
> > 
> > We can use it to guarantee mod tidy if we integrate it into CI check progress later
> 
> Looks this just show diff of go.sum, so why not use `git diff`

That's also ok to me, the main target is to add tidy check into `Makefile` (then we can aggregate other static check into one command), the implementation doesn't make matter.

**Comment by Rory-Z** [comment]
> That's also ok to me, the main target is to add tidy check into `Makefile` (then we can aggregate other static check into one command), the implementation doesn't make matter.

Maybe we can add `go mod tidy && git diff .` to Makefile, doesn't need script file ?

**Comment by Yisaer** [comment]
> > That's also ok to me, the main target is to add tidy check into `Makefile` (then we can aggregate other static check into one command), the implementation doesn't make matter.
> 
> Maybe we can add `go mod tidy && git diff .` to Makefile, doesn't need script file ?

updated.

**Review by Rory-Z — APPROVED** [review]

**Pull request merged**
