### PR TITLE
docs: fix syntax error in readme

### PR DESCRIPTION
**Pull request by buildcomplete**
Changed "written on" Go to "written in go"

### CODE REVIEW

**Comment by ngjaying** [comment]
Thanks @buildcomplete , please follow the Details link in DCO check to pass it firstly.

**Review by Yisaer — APPROVED** [review]

**Comment by ngjaying** [comment]
@buildcomplete Could you please take 5 minutes to sign the commit? Feel free to contact us if you have difficulties to do that. Thanks!

**Comment by ngjaying** [comment]
> hi @ngjaying, I am not sure how to do it as I am not used to working with GIT, can I do it from github?

ah, unfortunately, github do not have the capability. Would you like to learn a little bit about git. https://github.com/lf-edge/ekuiper/pull/2421/checks?check_run_id=18754132161

**Comment by buildcomplete** [comment]
Thanks for completing the request, was having difficulty with coorporate network blocking git🪓 will remember the signoff for future.

**Comment by ngjaying** [comment]
> Thanks for completing the request, was having difficulty with coorporate network blocking git🪓 will remember the signoff for future.

It is not easy to set it up for new commers. You may want to share the tutorial if you can get it work. Appreciate your contribution to the project. Thank you.

**Pull request merged**
