### PR TITLE
chore: Improved Error Handling and User Messages

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
## Description
This pull request enhances the error handling and user messaging in the codebase. The following improvements have been made:

- **Enhanced Error Handling:** I've introduced more robust error handling to provide detailed error messages when issues occur, making it easier to identify and troubleshoot problems.
- **Informative User Messages:** The code now provides informative messages to the user, improving the overall user experience. Users will receive clear and helpful messages to guide them through the application's processes.
- **Code Readability:** While the primary focus of this pull request is on error handling and user messages, I've also maintained good code formatting and readability.

These improvements aim to make the application more user-friendly and maintainable. Feel free to review the changes, and your feedback is highly appreciated.

### CODE REVIEW

**Comment by adarsh-jha-dev** [comment]
@Yisaer I request you to please have a look at this and let me know if the changes are relevant

**Review by Yisaer — APPROVED** [review]

**Comment by adarsh-jha-dev** [comment]
@Yisaer ,I request you that if you are satisfied with the changes, could you please merge it?

**Comment by ngjaying** [comment]
Merged, thank you!

**Comment by manansethi23** [comment]
Hey @adarsh-jha-dev Could you pls reach out to manan.sethi@emqx.io or alternatively provide me with yours. Needed to connect with you regarding hacktoberfest goodies :)

**Comment by adarsh-jha-dev** [comment]
> Hey @adarsh-jha-dev Could you pls reach out to [manan.sethi@emqx.io](mailto:manan.sethi@emqx.io) or alternatively provide me with yours. Needed to connect with you regarding hacktoberfest goodies :)

Could you please let me know what details I have to give for the Hacktoberfest goodies?

**Comment by adarsh-jha-dev** [comment]
> Hey @adarsh-jha-dev Could you pls reach out to [manan.sethi@emqx.io](mailto:manan.sethi@emqx.io) or alternatively provide me with yours. Needed to connect with you regarding hacktoberfest goodies :)

Hey @manansethi23 , I have sent you an email with all my details , I request you to please let me know if I have missed something, my email : adarshjhaxif@gmail.com

**Pull request merged**
